const t = {
	device: {
		id: '83354e8c83e83154a659f6a24c4cd0a9412b56e0',
		is_active: True,
		is_private_session: False,
		is_restricted: False,
		name: 'PLOP',
		supports_volume: True,
		type: 'Computer',
		volume_percent: 24,
	},
	shuffle_state: False,
	smart_shuffle: False,
	repeat_state: 'off',
	timestamp: 1719421552199,
	context: {
		external_urls: { spotify: 'https://open.spotify.com/playlist/37i9dQZF1EQpj7X7UK8OOF' },
		href: 'https://api.spotify.com/v1/playlists/37i9dQZF1EQpj7X7UK8OOF',
		type: 'playlist',
		uri: 'spotify:playlist:37i9dQZF1EQpj7X7UK8OOF',
	},
	progress_ms: 139514,
	item: {
		album: {
			album_type: 'single',
			artists: [
				{
					external_urls: { spotify: 'https://open.spotify.com/artist/3XSZyY300hJOLVc9KQLlee' },
					href: 'https://api.spotify.com/v1/artists/3XSZyY300hJOLVc9KQLlee',
					id: '3XSZyY300hJOLVc9KQLlee',
					name: 'Sleeping Wolf',
					type: 'artist',
					uri: 'spotify:artist:3XSZyY300hJOLVc9KQLlee',
				},
			],
			available_markets: [
				'AR',
				'AU',
				'AT',
				'BE',
				'BO',
				'BR',
				'BG',
				'CA',
				'CL',
				'CO',
				'CR',
				'CY',
				'CZ',
				'DK',
				'DO',
				'DE',
				'EC',
				'EE',
				'SV',
				'FI',
				'FR',
				'GR',
				'GT',
				'HN',
				'HK',
				'HU',
				'IS',
				'IE',
				'IT',
				'LV',
				'LT',
				'LU',
				'MY',
				'MT',
				'MX',
				'NL',
				'NZ',
				'NI',
				'NO',
				'PA',
				'PY',
				'PE',
				'PH',
				'PL',
				'PT',
				'SG',
				'SK',
				'ES',
				'SE',
				'CH',
				'TW',
				'TR',
				'UY',
				'US',
				'GB',
				'AD',
				'LI',
				'MC',
				'ID',
				'JP',
				'TH',
				'VN',
				'RO',
				'IL',
				'ZA',
				'SA',
				'AE',
				'BH',
				'QA',
				'OM',
				'KW',
				'EG',
				'MA',
				'DZ',
				'TN',
				'LB',
				'JO',
				'PS',
				'IN',
				'KZ',
				'MD',
				'UA',
				'SI',
				'KR',
				'BD',
				'PK',
				'LK',
				'GH',
				'KE',
				'NG',
				'TZ',
				'UG',
				'AG',
				'AM',
				'BS',
				'BB',
				'BZ',
				'BT',
				'BW',
				'BF',
				'CV',
				'CW',
				'DM',
				'FJ',
				'GM',
				'GE',
				'GD',
				'GW',
				'GY',
				'HT',
				'JM',
				'KI',
				'LS',
				'MW',
				'MV',
				'ML',
				'MH',
				'FM',
				'NA',
				'NR',
				'NE',
				'PW',
				'PG',
				'PR',
				'WS',
				'SM',
				'ST',
				'SN',
				'SC',
				'SL',
				'SB',
				'KN',
				'LC',
				'VC',
				'SR',
				'TL',
				'TO',
				'TT',
				'TV',
				'VU',
				'AZ',
				'BN',
				'BI',
				'KH',
				'CM',
				'TD',
				'KM',
				'GQ',
				'SZ',
				'GA',
				'GN',
				'KG',
				'LA',
				'MO',
				'MR',
				'MN',
				'NP',
				'RW',
				'TG',
				'UZ',
				'BJ',
				'MG',
				'MU',
				'MZ',
				'AO',
				'DJ',
				'ZM',
				'CG',
				'TJ',
				'VE',
				'ET',
			],
			external_urls: { spotify: 'https://open.spotify.com/album/1c8Qsml8C1IX6laAlAXqAe' },
			href: 'https://api.spotify.com/v1/albums/1c8Qsml8C1IX6laAlAXqAe',
			id: '1c8Qsml8C1IX6laAlAXqAe',
			images: [
				{ height: 640, url: 'https://i.scdn.co/image/ab67616d0000b2732bb0b0a1b46d5b16aeb82bf7', width: 640 },
				{ height: 300, url: 'https://i.scdn.co/image/ab67616d00001e022bb0b0a1b46d5b16aeb82bf7', width: 300 },
				{ height: 64, url: 'https://i.scdn.co/image/ab67616d000048512bb0b0a1b46d5b16aeb82bf7', width: 64 },
			],
			name: 'The Silent Ones',
			release_date: '2017-08-11',
			release_date_precision: 'day',
			total_tracks: 6,
			type: 'album',
			uri: 'spotify:album:1c8Qsml8C1IX6laAlAXqAe',
		},
		artists: [
			{
				external_urls: { spotify: 'https://open.spotify.com/artist/3XSZyY300hJOLVc9KQLlee' },
				href: 'https://api.spotify.com/v1/artists/3XSZyY300hJOLVc9KQLlee',
				id: '3XSZyY300hJOLVc9KQLlee',
				name: 'Sleeping Wolf',
				type: 'artist',
				uri: 'spotify:artist:3XSZyY300hJOLVc9KQLlee',
			},
		],
		available_markets: [
			'AR',
			'AU',
			'AT',
			'BE',
			'BO',
			'BR',
			'BG',
			'CA',
			'CL',
			'CO',
			'CR',
			'CY',
			'CZ',
			'DK',
			'DO',
			'DE',
			'EC',
			'EE',
			'SV',
			'FI',
			'FR',
			'GR',
			'GT',
			'HN',
			'HK',
			'HU',
			'IS',
			'IE',
			'IT',
			'LV',
			'LT',
			'LU',
			'MY',
			'MT',
			'MX',
			'NL',
			'NZ',
			'NI',
			'NO',
			'PA',
			'PY',
			'PE',
			'PH',
			'PL',
			'PT',
			'SG',
			'SK',
			'ES',
			'SE',
			'CH',
			'TW',
			'TR',
			'UY',
			'US',
			'GB',
			'AD',
			'LI',
			'MC',
			'ID',
			'JP',
			'TH',
			'VN',
			'RO',
			'IL',
			'ZA',
			'SA',
			'AE',
			'BH',
			'QA',
			'OM',
			'KW',
			'EG',
			'MA',
			'DZ',
			'TN',
			'LB',
			'JO',
			'PS',
			'IN',
			'KZ',
			'MD',
			'UA',
			'SI',
			'KR',
			'BD',
			'PK',
			'LK',
			'GH',
			'KE',
			'NG',
			'TZ',
			'UG',
			'AG',
			'AM',
			'BS',
			'BB',
			'BZ',
			'BT',
			'BW',
			'BF',
			'CV',
			'CW',
			'DM',
			'FJ',
			'GM',
			'GE',
			'GD',
			'GW',
			'GY',
			'HT',
			'JM',
			'KI',
			'LS',
			'MW',
			'MV',
			'ML',
			'MH',
			'FM',
			'NA',
			'NR',
			'NE',
			'PW',
			'PG',
			'PR',
			'WS',
			'SM',
			'ST',
			'SN',
			'SC',
			'SL',
			'SB',
			'KN',
			'LC',
			'VC',
			'SR',
			'TL',
			'TO',
			'TT',
			'TV',
			'VU',
			'AZ',
			'BN',
			'BI',
			'KH',
			'CM',
			'TD',
			'KM',
			'GQ',
			'SZ',
			'GA',
			'GN',
			'KG',
			'LA',
			'MO',
			'MR',
			'MN',
			'NP',
			'RW',
			'TG',
			'UZ',
			'BJ',
			'MG',
			'MU',
			'MZ',
			'AO',
			'DJ',
			'ZM',
			'CG',
			'TJ',
			'VE',
			'ET',
		],
		disc_number: 1,
		duration_ms: 208440,
		explicit: False,
		external_ids: { isrc: 'TCADE1772654' },
		external_urls: { spotify: 'https://open.spotify.com/track/35fU7yL8f6QDZz663U05O4' },
		href: 'https://api.spotify.com/v1/tracks/35fU7yL8f6QDZz663U05O4',
		id: '35fU7yL8f6QDZz663U05O4',
		is_local: False,
		name: 'Love Is the Cure',
		popularity: 31,
		preview_url: 'https://p.scdn.co/mp3-preview/556c212e591b1649f76f84a333759d15ee4b8446?cid=d07173af2fb14b1aa5feb8765f00fb59',
		track_number: 3,
		type: 'track',
		uri: 'spotify:track:35fU7yL8f6QDZz663U05O4',
	},
	currently_playing_type: 'track',
	actions: { disallows: { resuming: True } },
	is_playing: True,
};
